# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'KtAiSample' do
  #use_frameworks!
  pod 'Toast'
  pod 'AFNetworking'
  pod 'KTAIAPISDK', :path => '.'
end
