# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ktaiapi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ktaiapi.proto',
  package='kt.gigagenie.ai.api',
  syntax='proto3',
  serialized_options=b'Z\022sttRestApi/grpcapi',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13proto/ktaiapi.proto\x12\x13kt.gigagenie.ai.api\"Z\n\x08reqKtStt\x12\x31\n\x06signal\x18\x01 \x01(\x0b\x32\x1f.kt.gigagenie.ai.api.controlMsgH\x00\x12\x11\n\x07pcmData\x18\x02 \x01(\x0cH\x00\x42\x08\n\x06sttReq\"\x7f\n\x08resKtStt\x12\x31\n\x06signal\x18\x01 \x01(\x0b\x32\x1f.kt.gigagenie.ai.api.controlMsgH\x00\x12\x36\n\tsttResult\x18\x02 \x01(\x0b\x32!.kt.gigagenie.ai.api.sttResultMsgH\x00\x42\x08\n\x06sttRes\"1\n\ncontrolMsg\x12\x0f\n\x07msgType\x18\x01 \x01(\t\x12\x12\n\nmsgPayload\x18\x02 \x01(\t\"N\n\x0csttResultMsg\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tstartTime\x18\x03 \x01(\x02\x12\x0f\n\x07\x65ndTime\x18\x04 \x01(\x02\x32]\n\x07KtAiApi\x12R\n\x0cktSttService\x12\x1d.kt.gigagenie.ai.api.reqKtStt\x1a\x1d.kt.gigagenie.ai.api.resKtStt\"\x00(\x01\x30\x01\x42\x14Z\x12sttRestApi/grpcapib\x06proto3'
)




_REQKTSTT = _descriptor.Descriptor(
  name='reqKtStt',
  full_name='kt.gigagenie.ai.api.reqKtStt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='kt.gigagenie.ai.api.reqKtStt.signal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pcmData', full_name='kt.gigagenie.ai.api.reqKtStt.pcmData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sttReq', full_name='kt.gigagenie.ai.api.reqKtStt.sttReq',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=44,
  serialized_end=134,
)


_RESKTSTT = _descriptor.Descriptor(
  name='resKtStt',
  full_name='kt.gigagenie.ai.api.resKtStt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='kt.gigagenie.ai.api.resKtStt.signal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sttResult', full_name='kt.gigagenie.ai.api.resKtStt.sttResult', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sttRes', full_name='kt.gigagenie.ai.api.resKtStt.sttRes',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=136,
  serialized_end=263,
)


_CONTROLMSG = _descriptor.Descriptor(
  name='controlMsg',
  full_name='kt.gigagenie.ai.api.controlMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgType', full_name='kt.gigagenie.ai.api.controlMsg.msgType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgPayload', full_name='kt.gigagenie.ai.api.controlMsg.msgPayload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=314,
)


_STTRESULTMSG = _descriptor.Descriptor(
  name='sttResultMsg',
  full_name='kt.gigagenie.ai.api.sttResultMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='kt.gigagenie.ai.api.sttResultMsg.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='kt.gigagenie.ai.api.sttResultMsg.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='kt.gigagenie.ai.api.sttResultMsg.startTime', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='kt.gigagenie.ai.api.sttResultMsg.endTime', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=394,
)

_REQKTSTT.fields_by_name['signal'].message_type = _CONTROLMSG
_REQKTSTT.oneofs_by_name['sttReq'].fields.append(
  _REQKTSTT.fields_by_name['signal'])
_REQKTSTT.fields_by_name['signal'].containing_oneof = _REQKTSTT.oneofs_by_name['sttReq']
_REQKTSTT.oneofs_by_name['sttReq'].fields.append(
  _REQKTSTT.fields_by_name['pcmData'])
_REQKTSTT.fields_by_name['pcmData'].containing_oneof = _REQKTSTT.oneofs_by_name['sttReq']
_RESKTSTT.fields_by_name['signal'].message_type = _CONTROLMSG
_RESKTSTT.fields_by_name['sttResult'].message_type = _STTRESULTMSG
_RESKTSTT.oneofs_by_name['sttRes'].fields.append(
  _RESKTSTT.fields_by_name['signal'])
_RESKTSTT.fields_by_name['signal'].containing_oneof = _RESKTSTT.oneofs_by_name['sttRes']
_RESKTSTT.oneofs_by_name['sttRes'].fields.append(
  _RESKTSTT.fields_by_name['sttResult'])
_RESKTSTT.fields_by_name['sttResult'].containing_oneof = _RESKTSTT.oneofs_by_name['sttRes']
DESCRIPTOR.message_types_by_name['reqKtStt'] = _REQKTSTT
DESCRIPTOR.message_types_by_name['resKtStt'] = _RESKTSTT
DESCRIPTOR.message_types_by_name['controlMsg'] = _CONTROLMSG
DESCRIPTOR.message_types_by_name['sttResultMsg'] = _STTRESULTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

reqKtStt = _reflection.GeneratedProtocolMessageType('reqKtStt', (_message.Message,), {
  'DESCRIPTOR' : _REQKTSTT,
  '__module__' : 'proto.ktaiapi_pb2'
  # @@protoc_insertion_point(class_scope:kt.gigagenie.ai.api.reqKtStt)
  })
_sym_db.RegisterMessage(reqKtStt)

resKtStt = _reflection.GeneratedProtocolMessageType('resKtStt', (_message.Message,), {
  'DESCRIPTOR' : _RESKTSTT,
  '__module__' : 'proto.ktaiapi_pb2'
  # @@protoc_insertion_point(class_scope:kt.gigagenie.ai.api.resKtStt)
  })
_sym_db.RegisterMessage(resKtStt)

controlMsg = _reflection.GeneratedProtocolMessageType('controlMsg', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLMSG,
  '__module__' : 'proto.ktaiapi_pb2'
  # @@protoc_insertion_point(class_scope:kt.gigagenie.ai.api.controlMsg)
  })
_sym_db.RegisterMessage(controlMsg)

sttResultMsg = _reflection.GeneratedProtocolMessageType('sttResultMsg', (_message.Message,), {
  'DESCRIPTOR' : _STTRESULTMSG,
  '__module__' : 'proto.ktaiapi_pb2'
  # @@protoc_insertion_point(class_scope:kt.gigagenie.ai.api.sttResultMsg)
  })
_sym_db.RegisterMessage(sttResultMsg)


DESCRIPTOR._options = None

_KTAIAPI = _descriptor.ServiceDescriptor(
  name='KtAiApi',
  full_name='kt.gigagenie.ai.api.KtAiApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=396,
  serialized_end=489,
  methods=[
  _descriptor.MethodDescriptor(
    name='ktSttService',
    full_name='kt.gigagenie.ai.api.KtAiApi.ktSttService',
    index=0,
    containing_service=None,
    input_type=_REQKTSTT,
    output_type=_RESKTSTT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KTAIAPI)

DESCRIPTOR.services_by_name['KtAiApi'] = _KTAIAPI

# @@protoc_insertion_point(module_scope)
